from pathlib import Path


env_path = Path("server/utils/environment_lifecycle.py")
env_text = env_path.read_text(encoding="utf-8")

old_runtime_probe = '''def runtime_supports_deepseek_thinking(python_path: Path) -> bool:\n    try:\n        result = subprocess.run(\n            [*_runtime_command(python_path, "pdf2zh_next"), "--help"],\n            capture_output=True,\n            text=True,\n            timeout=45,\n        )\n        output = (result.stdout or "") + "\\n" + (result.stderr or "")\n        return result.returncode == 0 and all(flag in output for flag in THINKING_FLAGS)\n    except Exception:\n        return False\n'''

new_runtime_probe = '''def runtime_supports_deepseek_thinking(python_path: Path) -> bool:\n    """Check DeepSeek V4 capability without importing or starting pdf2zh_next.\n\n    pdf2zh_next 2.9.0 imports BabelDOC/high-level modules before its CLI parser\n    runs, so ``pdf2zh_next --help`` is not a safe health probe: on some Macs it\n    can spend more than a minute in import/asset initialization.  We instead\n    inspect the installed distribution files using importlib.metadata from the\n    target interpreter.  This verifies both DeepSeek setting fields and the\n    generic underscore-to-hyphen CLI argument generation used upstream.\n    """\n    code = (\n        "import json; "\n        "from importlib.metadata import distribution; "\n        "from pathlib import Path; "\n        "out={'supported': False, 'reason': ''}; "\n        "\\ntry:\\n"\n        "    dist=distribution('pdf2zh-next')\\n"\n        "    settings=Path(dist.locate_file('pdf2zh_next/config/translate_engine_model.py'))\\n"\n        "    cli=Path(dist.locate_file('pdf2zh_next/config/main.py'))\\n"\n        "    settings_text=settings.read_text(encoding='utf-8')\\n"\n        "    cli_text=cli.read_text(encoding='utf-8')\\n"\n        "    fields=('deepseek_thinking_mode','deepseek_reasoning_effort')\\n"\n        "    field_ok=all(field in settings_text for field in fields)\\n"\n        "    cli_ok='field_name.replace(\\\"_\\\", \\\"-\\\").lower()' in cli_text\\n"\n        "    out={'supported': bool(field_ok and cli_ok), 'reason': 'ok' if field_ok and cli_ok else 'missing-fields-or-cli-mapping'}\\n"\n        "except Exception as exc:\\n"\n        "    out={'supported': False, 'reason': type(exc).__name__ + ': ' + str(exc)}\\n"\n        "print(json.dumps(out))"\n    )\n    try:\n        result = subprocess.run(\n            [str(python_path), "-c", code],\n            cwd=SERVER_ROOT,\n            capture_output=True,\n            text=True,\n            timeout=20,\n        )\n        if result.returncode != 0:\n            return False\n        payload = json.loads(result.stdout.strip() or "{}")\n        return bool(payload.get("supported"))\n    except Exception:\n        return False\n'''

if old_runtime_probe not in env_text:
    raise SystemExit("Could not locate old runtime_supports_deepseek_thinking implementation")
env_text = env_text.replace(old_runtime_probe, new_runtime_probe, 1)

old_validate_runtime = '''        module = "pdf2zh_next" if engine == "pdf2zh_next" else "pdf2zh"\n        help_result = subprocess.run(\n            [*_runtime_command(python_path, module), "--help"],\n            cwd=SERVER_ROOT,\n            capture_output=True,\n            text=True,\n            timeout=60,\n        )\n        if help_result.returncode != 0:\n            print(f"❌ {module} --help 检查失败")\n            return False\n        if require_deepseek_thinking and engine == "pdf2zh_next":\n            output = (help_result.stdout or "") + "\\n" + (help_result.stderr or "")\n            if not all(flag in output for flag in THINKING_FLAGS):\n                print("❌ pdf2zh_next 缺少 DeepSeek V4 thinking flags")\n                return False\n        return True\n'''

new_validate_runtime = '''        module = "pdf2zh_next" if engine == "pdf2zh_next" else "pdf2zh"\n        env_dir = python_path.parent.parent\n        executable = _bin_dir(env_dir) / (\n            module + (".exe" if platform.system() == "Windows" else "")\n        )\n        if not executable.exists():\n            print(f"❌ {module} CLI 入口不存在: {executable}")\n            return False\n\n        # Do not execute ``pdf2zh_next --help`` here.  Upstream imports\n        # BabelDOC/high-level modules before CLI parsing, so --help can be a\n        # heavyweight operation and is not a reliable installation probe.\n        if require_deepseek_thinking and engine == "pdf2zh_next":\n            if not runtime_supports_deepseek_thinking(python_path):\n                print("❌ pdf2zh_next 缺少 DeepSeek V4 thinking capability")\n                return False\n        return True\n'''

if old_validate_runtime not in env_text:
    raise SystemExit("Could not locate old validate_environment runtime block")
env_text = env_text.replace(old_validate_runtime, new_validate_runtime, 1)
env_path.write_text(env_text, encoding="utf-8")


deep_path = Path("server/utils/deepseek_thinking.py")
deep_text = deep_path.read_text(encoding="utf-8")
if "import shutil\n" not in deep_text:
    deep_text = deep_text.replace("import os\n", "import os\nimport shutil\n", 1)

old_supports = '''def _runtime_supports_thinking(\n    invocation_prefix: list[str],\n    env: dict[str, str] | None = None,\n    cwd: str | None = None,\n) -> bool:\n    cache_key = tuple(invocation_prefix + ([f"cwd={cwd}"] if cwd else []))\n    if cache_key in _RUNTIME_CAPABILITY_CACHE:\n        return _RUNTIME_CAPABILITY_CACHE[cache_key]\n\n    try:\n        result = subprocess.run(\n            [*invocation_prefix, "--help"],\n            capture_output=True,\n            text=True,\n            timeout=30,\n            env=env,\n            cwd=cwd,\n        )\n        output = (result.stdout or "") + "\\n" + (result.stderr or "")\n        supported = (\n            result.returncode == 0\n            and THINKING_MODE_FLAG in output\n            and REASONING_EFFORT_FLAG in output\n        )\n    except Exception:\n        supported = False\n\n    _RUNTIME_CAPABILITY_CACHE[cache_key] = supported\n    return supported\n'''

new_supports = '''def _python_for_invocation_prefix(invocation_prefix: list[str]) -> Path | None:\n    """Resolve the Python interpreter behind a normal pdf2zh_next launcher."""\n    if (\n        len(invocation_prefix) >= 3\n        and invocation_prefix[1] == "-m"\n        and invocation_prefix[2] == "pdf2zh_next"\n    ):\n        candidate = Path(invocation_prefix[0])\n        return candidate if candidate.exists() else None\n\n    raw = invocation_prefix[0] if invocation_prefix else ""\n    resolved = shutil.which(raw) or raw\n    if not resolved:\n        return None\n    executable = Path(resolved)\n    if not executable.exists():\n        return None\n\n    names = ["python.exe"] if os.name == "nt" else ["python", "python3"]\n    for name in names:\n        candidate = executable.parent / name\n        if candidate.exists():\n            return candidate\n    return None\n\n\ndef _runtime_supports_thinking(\n    invocation_prefix: list[str],\n    env: dict[str, str] | None = None,\n    cwd: str | None = None,\n) -> bool:\n    cache_key = tuple(invocation_prefix + ([f"cwd={cwd}"] if cwd else []))\n    if cache_key in _RUNTIME_CAPABILITY_CACHE:\n        return _RUNTIME_CAPABILITY_CACHE[cache_key]\n\n    python_path = _python_for_invocation_prefix(invocation_prefix)\n    if python_path is not None:\n        # Normal uv/conda/system-Python installations can be inspected through\n        # their distribution metadata without starting the heavyweight CLI.\n        from utils.environment_lifecycle import runtime_supports_deepseek_thinking\n\n        supported = runtime_supports_deepseek_thinking(python_path)\n    else:\n        # Opaque standalone executables (notably the optional Windows bundle)\n        # have no inspectable Python environment, so --help remains the only\n        # capability signal.  Keep this fallback isolated to that path.\n        try:\n            result = subprocess.run(\n                [*invocation_prefix, "--help"],\n                capture_output=True,\n                text=True,\n                timeout=30,\n                env=env,\n                cwd=cwd,\n            )\n            output = (result.stdout or "") + "\\n" + (result.stderr or "")\n            supported = (\n                result.returncode == 0\n                and THINKING_MODE_FLAG in output\n                and REASONING_EFFORT_FLAG in output\n            )\n        except Exception:\n            supported = False\n\n    _RUNTIME_CAPABILITY_CACHE[cache_key] = supported\n    return supported\n'''

if old_supports not in deep_text:
    raise SystemExit("Could not locate old _runtime_supports_thinking implementation")
deep_text = deep_text.replace(old_supports, new_supports, 1)
deep_path.write_text(deep_text, encoding="utf-8")
